language: python
python:
  - "3.4.5"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirement.txt
  - pip install codecov
script:
  - pytest test/
after_success:
  - py.test --cov=app test/
